import { NextResponse } from "next/server";
import { CHAMPIONS } from "@/lib/champions";
import { packModpkg, slugify } from "@/lib/modpkg/pack";

export const runtime = "nodejs";

type TexturePayload = {
  path: string;
  dataBase64: string;
};

type ExportBody = {
  championId: string;
  skinName: string;
  author?: string;
  description?: string;
  textures: TexturePayload[];
  thumbnailBase64?: string;
};

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as ExportBody;

    if (!body.championId || !body.skinName?.trim()) {
      return NextResponse.json(
        { error: "championId and skinName are required" },
        { status: 400 },
      );
    }
    if (!Array.isArray(body.textures) || body.textures.length === 0) {
      return NextResponse.json(
        { error: "At least one recolored texture is required" },
        { status: 400 },
      );
    }

    const champion = CHAMPIONS.find((c) => c.id === body.championId);
    if (!champion) {
      return NextResponse.json({ error: "Unknown champion" }, { status: 400 });
    }

    const displayName = body.skinName.trim();
    const name = slugify(`${champion.id}-${displayName}`) || `skin-${Date.now()}`;
    const author = body.author?.trim() || "Custom Skin Lab";
    const description =
      body.description?.trim() ||
      `Recolored ${champion.name} skin generated with Custom Skin Lab.`;

    const chunks = body.textures.map((t) => ({
      path: t.path.replace(/^\/+/, ""),
      wad: champion.wad,
      layer: "base",
      data: new Uint8Array(Buffer.from(t.dataBase64, "base64")),
    }));

    const readme = `# ${displayName}

Champion: ${champion.name}
Generated by Custom Skin Lab

## Install
1. Open League Toolkit Manager
2. Import this \`.modpkg\`
3. Enable the mod and launch League

## Notes
v1 packs recolored textures into a champion WAD overlay.
Use asset paths that match your extracted textures for best results.
`;

    const thumbnail = body.thumbnailBase64
      ? new Uint8Array(Buffer.from(body.thumbnailBase64, "base64"))
      : undefined;

    const modpkg = await packModpkg({
      metadata: {
        schema_version: 3,
        name,
        display_name: displayName,
        description,
        version: "1.0.0",
        authors: [{ name: author, role: "creator" }],
        license: { type: "none" },
        tags: ["champion-skin", "recolor"],
        champions: [champion.id],
        maps: [],
        layers: [{ name: "base", priority: 0, description: "Base layer" }],
      },
      chunks,
      readme,
      thumbnail,
    });

    const filename = `${name}_1.0.0.modpkg`;
    return new NextResponse(new Uint8Array(modpkg), {
      status: 200,
      headers: {
        "Content-Type": "application/octet-stream",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("export failed", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Export failed" },
      { status: 500 },
    );
  }
}
